config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, skip: [:sessions]
  as :user do
    delete 'users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'home#index'
  resources :services, except: [:show, :new, :edit] do
    member do
      post :disable
      post :enable
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
  FREQUENCY = %w( daily weekly monthly )

  belongs_to :user

  validates :notification_date, :mobile_number, presence: true
  validates :name, presence: true, uniqueness: true
  validates :frequency, presence: true, inclusion: { in: FREQUENCY }
  validates :description, presence: true, length: { maximum: 140 }
  validates :custom_message, length: { maximum: 140 }

  def notify_service
    message = custom_message.empty? ? "I need a #{name}. Kindly deliver at #{user.address} and look for #{user.first_name} #{user.last_name}" : custom_message
    client = Chikka::Client.new(client_id: "#{Rails.application.secrets.chikka_client_id}",
                                secret_key: "#{Rails.application.secrets.chikka_secret_key}",
                                shortcode: "#{Rails.application.secrets.chikka_shortcode}")
    client.send_message(message: message, mobile_number: mobile_number)
  end

  def notify_user
    message = "You are running out of #{name}, but don't worry I will order it for you in the next five minutes."
    client = Chikka::Client.new(client_id: "#{Rails.application.secrets.chikka_client_id}",
                                secret_key: "#{Rails.application.secrets.chikka_secret_key}",
                                shortcode: "#{Rails.application.secrets.chikka_shortcode}")
    client.send_message(message: message, mobile_number: user.mobile_number)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable, :omniauthable

  has_many :services

  validates :first_name, :last_name, :email, :password, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.avatar = auth.info.image
      user.address = auth.info.location
      user.birth_date = auth.extra.raw_info.birthday
      user.gender = auth.extra.raw_info.gender
    end
  end

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def index
    @services = current_user.services
    @service = Service.new(user: current_user)
  end

  def create
    @service = current_user.services.new(service_params)

    if @service.save
      NotificationWorker.perform_async(@service.id)
      flash[:success] = 'Service successfully added'
      redirect_to services_path
    else
      flash[:error] = @service.errors.full_messages
      redirect_to services_path
    end
  end

  def update
    @service = current_user.services.find(params[:id])

    if @service.update(service_params)
      flash[:success] = 'Service successfully updated'
      redirect_to services_path
    else
      flash[:error] =  @service.errors.full_messages
      render :edit
    end
  end

  def destroy
    @service = current_user.services.find(params[:id])
    @service.destroy
    flash[:success] = 'Service successfully deleted'
    redirect_to services_path
  end

  def disable
    @service = current_user.services.find(params[:id])
    @service.update(enabled: false)
  end

  def enable
    @service = current_user.services.find(params[:id])
    @service.update(enabled: true)
  end

private

  def service_params
    params.require(:service).permit(:name, :description, :notification_date, :frequency, :mobile_number, :custom_message)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:success] = 'Signed in successfully.'
      sign_in @user, event: :authentication
      redirect_to services_path
    else
      flash[:error] = 'Something went wrong.'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.haml
%section.section-hero
  .container
    .row
      .hero-caption
        %h1.caption Enlist.it,  Aggregate &amp; Automate!
        %p.description Enables you to automate on time to any services you frequently subscribe. And let it do your routine services.
      .hero-images
        = image_tag 'hero-image.png', class: 'img-responsive'
%section.section-features
  .container
    .row
      .featured-lisitng
        = image_tag 'icn-access.png'
        %h3.title Access
      .featured-lisitng
        = image_tag 'icn-settings.png'
        %h3.title Add Services
      .featured-lisitng
        = image_tag 'icn-frequency.png'
        %h3.title Set frequency
      .featured-lisitng
        = image_tag 'icn-automate.png'
        %h3.title Automate

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Enlist
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/public/header'
    = yield
    = render 'shared/notification'

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title Enlist.it - Dashboard
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    %meta{ content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible' }
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:400,700'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    = render 'shared/dashboard/header'
    = yield
    = render 'shared/notification'

app/views/services/index.haml
.section-listing
  .container
    - if @services.empty?
      .services.-empty
        %h2.notice
          Add a new services
          %br>
          Create by tapping on the box buttton below
        .card-listing
          .services-card.-new{"data-target" => "#new-service", "data-toggle" => "modal"}
            %span.btn-add
              %span.ti-plus
                %br
              %p Add new Services
    - else
      .services
        - @services.each do |service|
          .card-listing
            %div{ class: "#{ service.enabled ? 'services-card -enable' : 'services-card -disabled' }" }
              .header
                %h3.title= service.name.capitalize
                .actions
                  %input{ checked: service.enabled, name: "service_#{service.id}_enabled", type: 'checkbox', id: "service_#{service.id}_enabled", class: 'enlist-radio' }
                  %label.checkbox-label{ "data-off" => "OFF", "data-on" => "ON", 'data-id' => service.id, for: "service_#{service.id}_enabled" }
              .details
                .contact
                  %p.field
                    %span.lbl Contact No.:
                    %span.area= service.mobile_number
                .frequency
                  %p.field
                    %span.lbl Frequency:
                    %span.area= service.frequency.capitalize
                .descriptions
                  %p.message= service.description.capitalize
              .footer
                .delete
                  = link_to service_path(service), method: :delete do
                    %i.ti-trash
                .settings
                  = link_to '#' do
                    %i.ti-settings
        .card-listing
          .services-card.-new{"data-target" => "#new-service", "data-toggle" => "modal"}
            .btn-add
              %span.ti-plus
              %p Add new Service
= render 'shared/dashboard/new_service_modal'

app/views/shared/_notification.haml
- flash.each do |name, message|
  - if name == 'notice'
    - name = 'success'
  - elsif name == 'alert' 
    - name = 'error'

  :javascript
    toastr.options = {
      'positionClass': 'toast-bottom-left'
    }
    toastr.#{name}("#{message}")

app/views/shared/dashboard/_header.haml
%body
  %header.header
    %nav.navbar.navbar-default.navbar-static-top{:role => "navigation"}
      / Brand and toggle get grouped for better mobile display
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"}
            = image_tag 'logo.png', height: 30
        / Collect the nav links, forms, and other content for toggling
        #navbar-collapse.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = image_tag current_user.avatar, width: 35, height: 35, class: 'img-circle'
                = current_user.fullname
                %b.caret
              %ul.dropdown-menu
                %li
                  %a{:href => "#"} Settings
                %li.divider
                %li
                  = link_to 'Logout', destroy_user_session_path, method: :delete

app/views/shared/dashboard/_new_service_modal.haml
#new-service.modal.fade{ role: 'dialog', tabindex: '-1', 'aria-labelledby' => 'myModalLabel' }
  .modal-dialog{ role: 'document' }
    .modal-content
      .modal-header
        %button.close{ 'aria-label' => 'Close', 'data-dismiss' => 'modal', type: 'button' }
          %span{ 'aria-hidden' => 'true' } ×
        %h4.modal-title Add New Service
      .modal-body
        = form_for @service, html: { role: 'form' } do |f|
          .fieldset
            .form-group
              = f.label :name
              = f.text_field :name, placeholder: 'Service Name', class: 'form-control'
            .row
              .col-lg-6
                .form-group
                  = f.label :notification_date
                  #datetimepicker.input-group.date{ role: 'datetime-picker' }
                    = f.text_field :notification_date, class: 'form-control', placeholder: 'Select Date'
                    %span.input-group-addon
                      %span.ti-calendar
              .col-lg-6
                .form-group
                  = f.label :frequency
                  = f.select :frequency, Service::FREQUENCY.map{ |x| [x.capitalize, x] }, { include_blank: 'Select frequency' }, { class: 'form-control', id: 'input-select' }
            .form-group
              = f.label :mobile_number, 'Service Contact No.'
              = f.text_field :mobile_number, placeholder: '09X-XXX-XXXX', class: 'form-control'
            .form-group
              = f.label :description
              = f.text_area :description, placeholder: 'Short Description', class: 'form-control'
            .form-group
              = f.label :custom_message
              = f.text_area :custom_message, placeholder: 'Leave this blank if you want to use the default', class: 'form-control'
            .form-group.clearfix
              .pull-right
                %button{ 'data-dismiss' => 'modal', type: 'button', class: 'btn btn-default' } Cancel
                = f.submit 'Save', class: 'btn btn-primary'